server:
  port: 80
  #context-path: /jlblog
  
#数据库连接配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jlblog
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    
#字符集和json格式工具
http:
   encoding:
     charset: utf-8
   converters:
     preferred-json-mapper: jackson
   multipart:
     max-file-size: 10MB
     
#加载log4j2
logging:
  config: classpath:log4j2.xml
  level: debug
  file:

#mynatis配置
mybatis:
  type-aliases-package: com.jlblog.jlblog.pojo
  #mapper加载路径
  mapper-locations: classpath:mapper/*Mapper.xml

#free